### ISSUE TITLE
Plans for the enclosure itself

### ISSUE THREAD

**Issue by schacon** [particle-iot/thermostat#2]
Do you have any of the plans for the enclosure itself online?

**Comment by joegoggins** [comment]
Not at the moment. Will see what I can pull together.

**Comment by zsup** [comment]
We can definitely add it. @mohitbhoite, can you add the enclosure files to
the repo?

Zach Supalla
Founder and CEO, Spark
312.953.3413

**Comment by joegoggins** [comment]
Mohit, if you can something to the readme as well ( describing and linking), that'd be sweet!

Thanks !

**Comment by joegoggins** [comment]
Hey Scott,

We pulled together a a few Google sketch-up files that characterize the plans for the enclosure and placed them in the [hardware/CAD](https://github.com/spark/thermostat/tree/master/hardware/CAD) folder. Also made a note about this on the [README here](https://github.com/spark/thermostat#physical-design)

Let me know if you need anything else or have other ideas for this project.

Thanks!

**Comment by schacon** [comment]
That's awesome, thanks!
