### ISSUE TITLE
I'm getting the following build errors on your web IDE

### ISSUE THREAD

**Issue by PranshuBansalDev** [particle-iot/thermostat#7]
Adafruit_GFX.cpp:39:0: warning: "pgm_read_byte" redefined [enabled by default]
  #define pgm_read_byte(addr) (_(const unsigned char *)(addr))
 ^
In file included from ../wiring/inc/spark_wiring.h:37:0,
                 from Adafruit_GFX.h:4,
                 from Adafruit_GFX.cpp:34:
../wiring/inc/spark_wiring_arduino.h:32:0: note: this is the location of the previous definition
 #define pgm_read_byte(x)  (_(x))
 ^
thermostat.cpp:8:18: error: variable or field 'setupMatrix' declared void
 void setupMatrix(Adafruit_8x8matrix m);
                  ^

thermostat.cpp:8:18: error: 'Adafruit_8x8matrix' was not declared in this scope
thermostat.cpp: In function 'void saveTemperature()':
thermostat.cpp:56:58: error: 'sFLASH_WriteBytes' was not declared in this scope
   matrix2.clear();
                                                          ^

thermostat.cpp: In function 'void setup()':
thermostat.cpp:111:3: warning: 'Spark' is deprecated (declared at ../wiring/inc/spark_wiring_cloud.h:270): Spark is now Particle. [-Wdeprecated-declarations]
 {
   ^
thermostat.cpp:113:3: warning: 'Spark' is deprecated (declared at ../wiring/inc/spark_wiring_cloud.h:270): Spark is now Particle. [-Wdeprecated-declarations]

   ^
thermostat.cpp:114:3: warning: 'Spark' is deprecated (declared at ../wiring/inc/spark_wiring_cloud.h:270): Spark is now Particle. [-Wdeprecated-declarations]
   matrix1.begin(0x70);
   ^
thermostat.cpp:115:3: warning: 'Spark' is deprecated (declared at ../wiring/inc/spark_wiring_cloud.h:270): Spark is now Particle. [-Wdeprecated-declarations]
   matrix2.begin(0x71);
   ^
thermostat.cpp:116:3: warning: 'Spark' is deprecated (declared at ../wiring/inc/spark_wiring_cloud.h:270): Spark is now Particle. [-Wdeprecated-declarations]
   matrix3.begin(0x72);
   ^
make[2]: **\* [../build/target/user/platform-0-lthermostat.o] Error 1
make[1]: **\* [user] Error 2
make: **\* [main] Error 2
Ready.

If I remove the include "application.h" I get the following build errors

Adafruit_GFX.cpp:39:0: warning: "pgm_read_byte" redefined [enabled by default]
  #define pgm_read_byte(addr) (_(const unsigned char *)(addr))
 ^
In file included from ../wiring/inc/spark_wiring.h:37:0,
                 from Adafruit_GFX.h:4,
                 from Adafruit_GFX.cpp:34:
../wiring/inc/spark_wiring_arduino.h:32:0: note: this is the location of the previous definition
 #define pgm_read_byte(x)  (_(x))
 ^
thermostat.cpp: In function 'void saveTemperature()':
thermostat.cpp:55:58: error: 'sFLASH_WriteBytes' was not declared in this scope
   matrix2.clear();
                                                          ^

thermostat.cpp: In function 'void setup()':
thermostat.cpp:110:3: warning: 'Spark' is deprecated (declared at ../wiring/inc/spark_wiring_cloud.h:270): Spark is now Particle. [-Wdeprecated-declarations]
 {
   ^
thermostat.cpp:112:3: warning: 'Spark' is deprecated (declared at ../wiring/inc/spark_wiring_cloud.h:270): Spark is now Particle. [-Wdeprecated-declarations]

   ^
thermostat.cpp:113:3: warning: 'Spark' is deprecated (declared at ../wiring/inc/spark_wiring_cloud.h:270): Spark is now Particle. [-Wdeprecated-declarations]
   matrix1.begin(0x70);
   ^
thermostat.cpp:114:3: warning: 'Spark' is deprecated (declared at ../wiring/inc/spark_wiring_cloud.h:270): Spark is now Particle. [-Wdeprecated-declarations]
   matrix2.begin(0x71);
   ^
thermostat.cpp:115:3: warning: 'Spark' is deprecated (declared at ../wiring/inc/spark_wiring_cloud.h:270): Spark is now Particle. [-Wdeprecated-declarations]
   matrix3.begin(0x72);
   ^
make[2]: **\* [../build/target/user/platform-0-lthermostat.o] Error 1
make[1]: **\* [user] Error 2
make: **\* [main] Error 2
Error: Could not compile. Please review your code.

**Comment by joegoggins** [comment]
Hey @pban1993 , thanks for bringing this up.

This thermostat project was built in a 24 hour hackathon to see what we could accomplish in very little time, few cheap components, and limited tools. We published the code and all of the ideas generated during this hackathon to inspire and illustrate what we came up with--we did not intend to support this codebase as a on-going aspect of our platform, thus, can't make any guarantees that this code will work on all future Particle firmware versions and devices.

It'd be interesting if at some point, if someone in the community wanted to rebuild this thermostat project as a library or as a Hackster.io project that could be maintained, etc. For the time being however, I'm gonna close this issue, because we will not be revisiting or updating this codebase any time soon.

Cheers,

-joe

**Comment by dmiddlecamp** [comment]
Shouldn't we keep this issue open until we resolve the bug?

**Comment by PranshuBansalDev** [comment]
Hey @joegoggins 

Is there any chance I could get the application.h file? I feel that might be causing the issue

**Comment by dmiddlecamp** [comment]
Hi @pban1993,

  You can find those here: https://github.com/spark/firmware

I'm guessing you just need the latest Adafruit GFX library ported to run on the photon and newer firmware... Can you give this one a try?  https://github.com/pkourany/Adafruit_mfGFX_IDE

Thanks,
David

**Comment by PranshuBansalDev** [comment]
@dmiddlecamp @joegoggins 

I solved the problems:
1) issues with the matrix
2) WriteBytes needs to be WriteBuffer (there was a change where WriteBytes was no longer supported externally)

I haven't tested it yet, but it compiles

http://pastebin.com/g1tjh0ht
